### ISSUE TITLE
mtRef = lxxRef

### ISSUE THREAD

**Issue by jcuenod** [adamb924/references-in-sqlite#1]
Have you used this data at all? I'm just curious (especially if you've made improvements). I noticed that this query returns no results:

```
select * from refs where lxxRef != mtRef;
```

**Comment by adamb924** [comment]
No I guess I haven't. :-) I'd done a little coding going between MT and English, but never MT and LXX. I had a copy/paste error in my import code, which I've now fixed. Thank you for the report. (Hope things are going well with you!)

**Comment by jcuenod** [comment]
Thanks for the rapid fix!
Hmm, I must say I was hoping this would look different in Exod 39...

Hope things are going well with you too! I'd love to know what you're up to these days...
